apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: faakhirzahid/video-convertor-auth
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"  # request 100 milliCPU (0.1 CPU)
              memory: "128Mi"  # request 128 MiB of memory
            limits:
              cpu: "500m"  # limit to 500 milliCPU (0.5 CPU)
              memory: "256Mi"  # limit to 256 MiB of memory
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
